"""add tool calls to conversation messages

Revision ID: 99acaa6df023
Revises: 51df234b0f67
Create Date: 2026-08-15 18:21:37.891577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99acaa6df023'
down_revision: Union[str, Sequence[str], None] = '51df234b0f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('tool_calls', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_conversation_messages_convesation_id'), table_name='conversation_messages')
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.create_index(op.f('ix_conversation_messages_convesation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.drop_column('conversation_messages', 'tool_calls')
    # ### end Alembic commands ###
