"""add oauth state to mcp connections

Revision ID: bed5c7ce8523
Revises: f284bd3ebe61
Create Date: 2026-08-20 17:27:46.998473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed5c7ce8523'
down_revision: Union[str, Sequence[str], None] = 'f284bd3ebe61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_connection', sa.Column('oauth_state', sa.String(length=255), nullable=True))
    op.add_column('mcp_connection', sa.Column('code_verifier', sa.Text(), nullable=True))
    op.create_index(op.f('ix_mcp_connection_oauth_state'), 'mcp_connection', ['oauth_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_connection_oauth_state'), table_name='mcp_connection')
    op.drop_column('mcp_connection', 'code_verifier')
    op.drop_column('mcp_connection', 'oauth_state')
    # ### end Alembic commands ###
