"""add oauth configuration to mcp servers

Revision ID: df9579ba0c28
Revises: f3f28bff0dfd
Create Date: 2026-08-20 15:38:49.749769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9579ba0c28'
down_revision: Union[str, Sequence[str], None] = 'f3f28bff0dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('auth_type', sa.String(length=50), server_default="none", nullable=False))
    op.add_column('mcp_servers', sa.Column('authorization_endpoint', sa.Text(), nullable=True))
    op.add_column('mcp_servers', sa.Column('token_endpoint', sa.Text(), nullable=True))
    op.add_column('mcp_servers', sa.Column('registration_endpoint', sa.Text(), nullable=True))
    op.add_column('mcp_servers', sa.Column('client_id', sa.Text(), nullable=True))
    op.add_column('mcp_servers', sa.Column('client_secret', sa.Text(), nullable=True))
    op.add_column('mcp_servers', sa.Column('scopes', sa.Text(), nullable=True))
    op.add_column('mcp_servers', sa.Column('supports_pkce', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'supports_pkce')
    op.drop_column('mcp_servers', 'scopes')
    op.drop_column('mcp_servers', 'client_secret')
    op.drop_column('mcp_servers', 'client_id')
    op.drop_column('mcp_servers', 'registration_endpoint')
    op.drop_column('mcp_servers', 'token_endpoint')
    op.drop_column('mcp_servers', 'authorization_endpoint')
    op.drop_column('mcp_servers', 'auth_type')
    # ### end Alembic commands ###
