"""remove generic oauth config from mcp servers

Revision ID: e8d8b28915cc
Revises: df9579ba0c28
Create Date: 2026-08-20 17:15:47.731034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d8b28915cc'
down_revision: Union[str, Sequence[str], None] = 'df9579ba0c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'supports_pkce')
    op.drop_column('mcp_servers', 'auth_type')
    op.drop_column('mcp_servers', 'authorization_endpoint')
    op.drop_column('mcp_servers', 'client_secret')
    op.drop_column('mcp_servers', 'token_endpoint')
    op.drop_column('mcp_servers', 'client_id')
    op.drop_column('mcp_servers', 'scopes')
    op.drop_column('mcp_servers', 'registration_endpoint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('registration_endpoint', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcp_servers', sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcp_servers', sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcp_servers', sa.Column('token_endpoint', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcp_servers', sa.Column('client_secret', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcp_servers', sa.Column('authorization_endpoint', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcp_servers', sa.Column('auth_type', sa.VARCHAR(length=50), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=False))
    op.add_column('mcp_servers', sa.Column('supports_pkce', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
