"""add connection provider to mcp servers

Revision ID: f284bd3ebe61
Revises: e8d8b28915cc
Create Date: 2026-08-20 17:19:55.469423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f284bd3ebe61'
down_revision: Union[str, Sequence[str], None] = 'e8d8b28915cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('connection_provider', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'connection_provider')
    # ### end Alembic commands ###
