"""add mcp connections

Revision ID: f3f28bff0dfd
Revises: 4f8a13eaf348
Create Date: 2026-08-20 15:24:07.211623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f28bff0dfd'
down_revision: Union[str, Sequence[str], None] = '4f8a13eaf348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_connection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mcp_server_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mcp_server_id', name='uq_user_mcp_server_connection')
    )
    op.create_index(op.f('ix_mcp_connection_mcp_server_id'), 'mcp_connection', ['mcp_server_id'], unique=False)
    op.create_index(op.f('ix_mcp_connection_user_id'), 'mcp_connection', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_connection_user_id'), table_name='mcp_connection')
    op.drop_index(op.f('ix_mcp_connection_mcp_server_id'), table_name='mcp_connection')
    op.drop_table('mcp_connection')
    # ### end Alembic commands ###
